"""initial schema (11 tables)

Revision ID: f9192eeddac1
Revises:
Create Date: 2026-09-16 16:56:42.228977

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f9192eeddac1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("original_name", sa.String(length=255), nullable=True),
        sa.Column("is_adopted", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("object_key", name=op.f("uq_assets_object_key")),
    )
    op.create_index(op.f("ix_assets_created_at"), "assets", ["created_at"], unique=False)
    op.create_index(op.f("ix_assets_is_adopted"), "assets", ["is_adopted"], unique=False)
    op.create_index(op.f("ix_assets_is_deleted"), "assets", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_assets_kind"), "assets", ["kind"], unique=False)
    op.create_index(op.f("ix_assets_task_id"), "assets", ["task_id"], unique=False)
    op.create_index(op.f("ix_assets_tenant_id"), "assets", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_assets_user_id"), "assets", ["user_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_ts"), "audit_logs", ["ts"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("workflow_id", sa.BigInteger(), nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=True),
        sa.Column("common_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("succeeded_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("canceled_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
    )
    op.create_index(op.f("ix_batches_created_at"), "batches", ["created_at"], unique=False)
    op.create_index(op.f("ix_batches_status"), "batches", ["status"], unique=False)
    op.create_index(op.f("ix_batches_tenant_id"), "batches", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_batches_user_id"), "batches", ["user_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("event_name", sa.String(length=64), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("task_id", sa.BigInteger(), nullable=True),
        sa.Column("batch_id", sa.BigInteger(), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("app_version", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_events_event_id")),
    )
    op.create_index("ix_events_name_ts", "events", ["event_name", "ts"], unique=False)
    op.create_index("ix_events_task", "events", ["task_id"], unique=False)
    op.create_index(op.f("ix_events_tenant_id"), "events", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_events_ts"), "events", ["ts"], unique=False)
    op.create_index("ix_events_user_ts", "events", ["user_id", "ts"], unique=False)
    op.create_table(
        "model_registry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("license", sa.String(length=128), nullable=True),
        sa.Column("license_url", sa.String(length=512), nullable=True),
        sa.Column("is_commercial_ok", sa.Boolean(), nullable=False),
        sa.Column("license_note", sa.Text(), nullable=True),
        sa.Column("eval_score", sa.Float(), nullable=True),
        sa.Column("good_rate", sa.Float(), nullable=True),
        sa.Column("eval_notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("enable_notes", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_registry")),
    )
    op.create_index(
        op.f("ix_model_registry_created_at"), "model_registry", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_model_registry_is_active"), "model_registry", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_model_registry_is_commercial_ok"),
        "model_registry",
        ["is_commercial_ok"],
        unique=False,
    )
    op.create_index(op.f("ix_model_registry_kind"), "model_registry", ["kind"], unique=False)
    op.create_index(op.f("ix_model_registry_name"), "model_registry", ["name"], unique=False)
    op.create_index(op.f("ix_model_registry_sha256"), "model_registry", ["sha256"], unique=False)
    op.create_table(
        "prompt_library",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("positive", sa.Text(), nullable=False),
        sa.Column("negative", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_library")),
    )
    op.create_index(
        op.f("ix_prompt_library_category"), "prompt_library", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_library_created_at"), "prompt_library", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_library_tenant_id"), "prompt_library", ["tenant_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=True),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.BigInteger(), nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("seed", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("engine_prompt_id", sa.String(length=64), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wait_seconds", sa.Float(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("gpu_seconds", sa.Float(), nullable=True),
        sa.Column("gpu_mem_peak_mb", sa.Float(), nullable=True),
        sa.Column("degrade_count", sa.Integer(), nullable=False),
        sa.Column("degrade_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_tasks_retry_count_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_batch_id"), "tasks", ["batch_id"], unique=False)
    op.create_index("ix_tasks_batch_status", "tasks", ["batch_id", "status"], unique=False)
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_tasks_engine_prompt_id"), "tasks", ["engine_prompt_id"], unique=False)
    op.create_index(op.f("ix_tasks_error_type"), "tasks", ["error_type"], unique=False)
    op.create_index(op.f("ix_tasks_heartbeat_at"), "tasks", ["heartbeat_at"], unique=False)
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index("ix_tasks_status_created", "tasks", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_tasks_tenant_id"), "tasks", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_index(op.f("ix_tasks_workflow_id"), "tasks", ["workflow_id"], unique=False)
    op.create_index(
        "uq_tasks_idempotency",
        "tasks",
        ["user_id", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "templates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("workflow_id", sa.BigInteger(), nullable=False),
        sa.Column("preset_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("example_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
    )
    op.create_index(op.f("ix_templates_category"), "templates", ["category"], unique=False)
    op.create_index(op.f("ix_templates_created_at"), "templates", ["created_at"], unique=False)
    op.create_index(op.f("ix_templates_is_active"), "templates", ["is_active"], unique=False)
    op.create_index(op.f("ix_templates_workflow_id"), "templates", ["workflow_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("quota_total", sa.Integer(), nullable=False),
        sa.Column("quota_used", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "workflows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("param_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("param_bindings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("eval_score", sa.Float(), nullable=True),
        sa.Column("good_rate", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
        sa.UniqueConstraint("name", "version", name="uq_workflows_name_version"),
    )
    op.create_index(op.f("ix_workflows_created_at"), "workflows", ["created_at"], unique=False)
    op.create_index(op.f("ix_workflows_is_active"), "workflows", ["is_active"], unique=False)
    op.create_index(op.f("ix_workflows_name"), "workflows", ["name"], unique=False)
    op.create_table(
        "defect_knowledge",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("defect_type", sa.String(length=64), nullable=False),
        sa.Column("symptom", sa.Text(), nullable=False),
        sa.Column("cause", sa.Text(), nullable=False),
        sa.Column("solution", sa.Text(), nullable=False),
        sa.Column("recommended_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("related_asset_id", sa.BigInteger(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defect_knowledge")),
    )
    op.create_index(
        op.f("ix_defect_knowledge_created_at"), "defect_knowledge", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_defect_knowledge_defect_type"), "defect_knowledge", ["defect_type"], unique=False
    )
    # 外键统一在所有表建好之后添加：模型之间存在环（assets→tasks→batches→templates→assets），
    # 内联外键无法排出合法建表顺序（PostgreSQL 上会 relation does not exist）。
    op.create_foreign_key(
        op.f("fk_assets_task_id_tasks"),
        "assets",
        "tasks",
        ["task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_assets_user_id_users"),
        "assets",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_batches_template_id_templates"),
        "batches",
        "templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_batches_user_id_users"),
        "batches",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_batches_workflow_id_workflows"),
        "batches",
        "workflows",
        ["workflow_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_defect_knowledge_related_asset_id_assets"),
        "defect_knowledge",
        "assets",
        ["related_asset_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_tasks_batch_id_batches"),
        "tasks",
        "batches",
        ["batch_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_tasks_template_id_templates"),
        "tasks",
        "templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_tasks_user_id_users"),
        "tasks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_tasks_workflow_id_workflows"),
        "tasks",
        "workflows",
        ["workflow_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_templates_example_asset_id_assets"),
        "templates",
        "assets",
        ["example_asset_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_templates_workflow_id_workflows"),
        "templates",
        "workflows",
        ["workflow_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先摘外键再删表：否则删父表会被子表的外键挡住（且这样与建表顺序无关）。
    op.drop_constraint(op.f("fk_assets_task_id_tasks"), "assets", type_="foreignkey")
    op.drop_constraint(op.f("fk_assets_user_id_users"), "assets", type_="foreignkey")
    op.drop_constraint(op.f("fk_batches_template_id_templates"), "batches", type_="foreignkey")
    op.drop_constraint(op.f("fk_batches_user_id_users"), "batches", type_="foreignkey")
    op.drop_constraint(op.f("fk_batches_workflow_id_workflows"), "batches", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_defect_knowledge_related_asset_id_assets"), "defect_knowledge", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_tasks_batch_id_batches"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("fk_tasks_template_id_templates"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("fk_tasks_user_id_users"), "tasks", type_="foreignkey")
    op.drop_constraint(op.f("fk_tasks_workflow_id_workflows"), "tasks", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_templates_example_asset_id_assets"), "templates", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_templates_workflow_id_workflows"), "templates", type_="foreignkey")
    op.drop_index(op.f("ix_defect_knowledge_defect_type"), table_name="defect_knowledge")
    op.drop_index(op.f("ix_defect_knowledge_created_at"), table_name="defect_knowledge")
    op.drop_table("defect_knowledge")
    op.drop_index(op.f("ix_workflows_name"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_is_active"), table_name="workflows")
    op.drop_index(op.f("ix_workflows_created_at"), table_name="workflows")
    op.drop_table("workflows")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_templates_workflow_id"), table_name="templates")
    op.drop_index(op.f("ix_templates_is_active"), table_name="templates")
    op.drop_index(op.f("ix_templates_created_at"), table_name="templates")
    op.drop_index(op.f("ix_templates_category"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(
        "uq_tasks_idempotency",
        table_name="tasks",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_tasks_workflow_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_tenant_id"), table_name="tasks")
    op.drop_index("ix_tasks_status_created", table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_heartbeat_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_error_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_engine_prompt_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.drop_index("ix_tasks_batch_status", table_name="tasks")
    op.drop_index(op.f("ix_tasks_batch_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_prompt_library_tenant_id"), table_name="prompt_library")
    op.drop_index(op.f("ix_prompt_library_created_at"), table_name="prompt_library")
    op.drop_index(op.f("ix_prompt_library_category"), table_name="prompt_library")
    op.drop_table("prompt_library")
    op.drop_index(op.f("ix_model_registry_sha256"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_name"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_kind"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_is_commercial_ok"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_is_active"), table_name="model_registry")
    op.drop_index(op.f("ix_model_registry_created_at"), table_name="model_registry")
    op.drop_table("model_registry")
    op.drop_index("ix_events_user_ts", table_name="events")
    op.drop_index(op.f("ix_events_ts"), table_name="events")
    op.drop_index(op.f("ix_events_tenant_id"), table_name="events")
    op.drop_index("ix_events_task", table_name="events")
    op.drop_index("ix_events_name_ts", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_batches_user_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_tenant_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_status"), table_name="batches")
    op.drop_index(op.f("ix_batches_created_at"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_ts"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_assets_user_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_tenant_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_task_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_kind"), table_name="assets")
    op.drop_index(op.f("ix_assets_is_deleted"), table_name="assets")
    op.drop_index(op.f("ix_assets_is_adopted"), table_name="assets")
    op.drop_index(op.f("ix_assets_created_at"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
